### ISSUE TITLE
%

### ISSUE THREAD

**Issue by Amor-Fairouz** [emomon23/XamarinPoorMansAccordion#1]
thks for sharing this i really apreciate it but how can i add a multiple Level with this 
any help ?

**Comment by emomon23** [comment]
You mean like a nested accordion?


-------- Original Message --------
Subject: [emomon23/XamarinPoorMansAccordion] % (#1)

**Comment by Amor-Fairouz** [comment]
yes  like this image below 
![expand](https://user-images.githubusercontent.com/15838445/26895864-4647f3e0-4bc3-11e7-8629-81ffd63a2973.PNG)

**Comment by emomon23** [comment]
It'd definitely doable.  I'd have to dig into it though, I'll look into it tonight and if I can figure it out in an hour or so, I'll send you some code.


-------- Original Message --------
Subject: Re: [emomon23/XamarinPoorMansAccordion] % (#1)

**Comment by Amor-Fairouz** [comment]
thank you for your reply and help  i'm  grateful

**Comment by emomon23** [comment]
get the latest code from github, run it, and take a look at the dynamic accordion, not pretty, but it should point you in the right direction


-------- Original Message --------
Subject: Re: [emomon23/XamarinPoorMansAccordion] % (#1)

**Comment by Amor-Fairouz** [comment]
thank you again
